# For more information see: https://help.github/actions/language-and

name: Nodel.js.CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://node.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'github-session1-webapp-jbs'
        slot-name: 'Staging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cc8d230be2384cf3bb3eb2af4bce4af5 }}
        package: .
